# Generated by Django 3.1 on 2020-08-11 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('photo', models.URLField(default='https://classeventie.classiebit.com//upload/users/images/1537002962360.png')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
