<<<<<<< HEAD
# Generated by Django 3.1 on 2020-08-11 08:30

=======
# Generated by Django 3.0.8 on 2020-08-08 06:22

from django.conf import settings
>>>>>>> Aida
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('auth', '0001_initial'),
=======
        ('auth', '0011_update_proxy_permissions'),
>>>>>>> Aida
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
<<<<<<< HEAD
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
=======
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
>>>>>>> Aida
                ('photo', models.URLField(default='https://robohash.org/suscipitnequeut.png?size=170x170&set=set1')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
