# Generated by Django 3.0.8 on 2020-08-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200806_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.URLField(default='https://robohash.org/suscipitnequeut.png?size=170x170&set=set1'),
        ),
    ]
