# Generated by Django 2.2.14 on 2020-08-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdata',
            old_name='DefenceRate',
            new_name='DefenceRateH',
        ),
    ]
