# Generated by Django 2.2.15 on 2020-08-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPrediction', '0002_prediction_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='vote',
            field=models.CharField(max_length=1),
        ),
    ]
