# Generated by Django 2.2.14 on 2020-08-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PsychicBits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teamLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
