# Generated by Django 3.0.8 on 2020-08-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PsychicBits', '0002_teamlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='AW_score',
            field=models.IntegerField(blank=True, default=0, max_length=2, verbose_name='Away Team Score'),
        ),
        migrations.AddField(
            model_name='match',
            name='HT_score',
            field=models.IntegerField(blank=True, default=0, max_length=2, verbose_name='Home Team Score'),
        ),
    ]
